name: hello-world

# Run this workflow every time a new commit pushed to your repository
on: push
jobs: 
  hello-world:
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    container: docker://alpine:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: iterative/setup-cml@v1
       
      - name: Test
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          cml-publish dog.jpg --md > report.md
          cml-send-comment report.md

