name: hello-world

# Run this workflow every time a new commit pushed to your repository
on: push
jobs: 
  hello-world:
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get CML
        uses: iterative/setup-cml@v1
      
      - run: |
          cml-publish dog.jpg --md > report.md
          cml-send-comment report.md

