name: hello-world

# Run this workflow every time a new commit pushed to your repository
on: push
jobs: 
  hello-world:
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6' 
      - uses: iterative/setup-cml@v1
       
      - name: "Train model and report"
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          pip install -r requirements.txt
          python train.py
          
          cat metrics.txt > report.md
          cml-publish confusion_matrix.png --md --title 'confusion-matrix' >> report.md
          cml-send-comment report.md 

